# Generated by Django 3.2.7 on 2021-09-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
