# Generated by Django 3.2.7 on 2021-09-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Customer',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='Customer',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
